App_library/urls.py
from django.conf.urls import url, include
from django.urls import path

from . import views

app_name = 'App_library'

urlpatterns = [
    url(r'^$', views.index, name='home'),
    url(r'^books$', views.books, name="books"),
    url(r'^categories$', views.categories, name="categories"),
    url(r'^customers$', views.customers, name="customers"),
    url(r'^returning$', views.returning, name="returning"),
    url(r'^borrow$', views.borrow, name="borrow"),
    path('edit_book/<int:pk>', views.book_edit, name="edit_book"),
    url(r'^edit_category/(\d+)/$', views.edit_category, name="edit_category"),
    url(r'^delete_book/(\d+)/$', views.delete_book, name="delete_book"),
    url(r'^delete_category/(\d+)/$', views.delete_category, name="delete_category"),
]

App_login/urls.py
from django.conf.urls import url
from django.urls import path

from App_login.views import *

app_name = 'App_login'

urlpatterns = [
    path('', login_view, name='defaultview'),
    path('signup/', signup_system, name='signup'),
    path('login', login_view, name='login'),
    path('logout', logout_view, name='logout'),
]

My_Library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_library.urls')),
    path('accounts/', include('App_login.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset.html'),
         name='password_reset'),
    path('reset-password-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset-password-done/',
         auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
         name='password_reset_complete'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_library/models.py
from django.core.validators import RegexValidator
from django.utils.translation import gettext_lazy as _
from django.db import models
from datetime import date


# Create your models here.

class Category(models.Model):
    title = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return f"{self.title}"


class BookLocation(models.Model):
    self_no = models.CharField(max_length=255)
    row_no = models.CharField(max_length=255)

    def __str__(self):
        return f"Self-{self.self_no}, Row-{self.row_no}"


class Book(models.Model):
    title = models.CharField(max_length=255, unique=True)
    categories = models.ForeignKey(Category, on_delete=models.CASCADE)
    cover = models.ImageField(upload_to='book_cover')
    author = models.CharField(max_length=255, unique=True)
    description = models.TextField(max_length=25000, blank=True, null=True)
    available = models.PositiveIntegerField(default=0)
    location = models.ForeignKey(BookLocation, on_delete=models.CASCADE, related_name='book_location')

    def __str__(self):
        return f"'{self.title}' by '{self.author}'"


class Customer(models.Model):
    NID = models.CharField(max_length=255, unique=True)
    firstname = models.CharField(max_length=255)
    lastname = models.CharField(max_length=255)
    Address = models.CharField(max_length=255)
    phone_regex = RegexValidator(regex=r"^\+?(88)01[3-9][0-9]{8}$", message=_(
        "Enter a valid Bangladesh mobile phone number starting with +(country code)"))
    phone_number = models.CharField(validators=[phone_regex], verbose_name=_("Mobile phone"), max_length=17,
                                    blank=False, null=True)
    year = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.firstname} {self.lastname}-{self.NID}"


class Borrow(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    qty = models.IntegerField(default=0)
    date = models.DateField(default=date.today)
    status = models.CharField(max_length=25)

App_library/forms.py
from django.contrib.auth.forms import forms
from App_library.models import *


class AddBookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = "__all__"


class BookBorrowForm(forms.ModelForm):
    class Meta:
        model = Borrow
        exclude = ['qty', 'date', 'status']


class BookEditForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'cover', 'author', 'description', 'available', 'location']


class AddNewSelf(forms.ModelForm):
    class Meta:
        model = BookLocation
        fields = ['self_no', 'row_no']

App_library/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponseRedirect
from django.db.models import Sum
from datetime import date
from datetime import datetime
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.views.generic import UpdateView
from App_library.models import *
from App_library.forms import *


# Create your views here.
@login_required
def index(request):
    return render(request, "App_library/Home.html")


@login_required
def categories(request):
    if request.method == "POST":
        title = request.POST.get('title')
        cat = Category(title=title)
        cat.save()
        return HttpResponseRedirect(reverse('App_library:categories'))
    all_categories = Category.objects.all()
    return render(request, "App_library/category.html", context={"categories": all_categories})


@login_required
def delete_category(request, id):
    category = Category.objects.filter(id=id)
    category.delete()
    return HttpResponseRedirect(reverse('App_library:categories'))


@login_required
def edit_category(request, id):
    category = Category.objects.filter(id=id).get()
    if request.method == 'POST':
        cat_title = request.POST.get('title')
        category.title = cat_title
        category.save()
        return HttpResponseRedirect(reverse('App_library:categories'))
    return render(request, 'App_library/edit_category.html', context={'category': category})


def books(request):
    form = AddBookForm()
    bookselfForm = AddNewSelf()
    if request.method == "POST" and 'save_book' in request.POST:
        form = AddBookForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
    elif request.method == "POST" and 'save_bookself' in request.POST:
        bookselfForm = AddNewSelf(request.POST)
        if bookselfForm.is_valid():
            bookselfForm.save()
    all_books = Book.objects.all()
    b = [x for x in all_books]
    if len(b) == 0:
        all_books = None
    all_categories = Category.objects.all()
    return render(request, "App_library/books.html",
                  {"books": all_books, 'b': b, "categories": all_categories, 'form': form, 'bookself': bookselfForm})


def book_edit(request, pk):
    book = Book.objects.get(pk=pk)
    form = BookEditForm(instance=book)
    if request.method == "POST":
        form = BookEditForm(request.POST, request.FILES, instance=book)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('App_library:books'))
    return render(request, 'App_library/book_edit.html', context={'form': form})


def delete_book(request, id):
    book = Book.objects.filter(id=id).get()
    book.delete()
    return redirect("/books")


def customers(request):
    if request.method == "POST":
        nid = request.POST["nid"]
        firstname = request.POST["firstname"]
        lastname = request.POST["lastname"]
        address = request.POST["address"]
        phone_number = request.POST["phone_number"]
        customer = Customer(NID=nid, firstname=firstname, lastname=lastname, Address=address, phone_number=phone_number)
        customer.save()
        return HttpResponseRedirect(reverse('App_library:customers'))
    all_Customers = Customer.objects.all()
    return render(request, "App_library/Customers.html", context={"Customers": all_Customers})


def borrow(request):
    form = BookBorrowForm()
    b = Borrow.objects.all()
    all_borrower = []
    for i in b:
        if i.status == 'Borrowed':
            borrower = f"{i.customer.firstname} {i.customer.lastname}-{i.customer.NID}"
            all_borrower.append(borrower)
    if request.method == "POST":
        form = BookBorrowForm(request.POST)
        if form.is_valid():
            bro = form.save(commit=False)
            customer = str(f"{bro.customer.firstname} {bro.customer.lastname}-{bro.customer.NID}")
            if customer in all_borrower:
                messages.info(request, "You didn't return your previous book!!!")
            else:
                print("Bad Coding!!!")
                bro.qty = 1
                bro.status = "Borrowed"
                bro.save()
            return HttpResponseRedirect(reverse('App_library:borrow'))
    _customers = Customer.objects.all()
    _books = Book.objects.all()
    datas = []
    for book in _books:
        left = Borrow.objects.filter(status="Borrowed", book__title=book.title).aggregate(Sum('qty'))
        if left['qty__sum'] is None:
            l = 0
        else:
            l = int(left['qty__sum'])
        datas.append(book.available - l)
    all_datum = zip(_books, datas)
    return render(request, "App_library/borrow.html", {"datas": all_datum, "customers": _customers, 'form': form})


def returning(request):
    if request.method == "POST":
        b_id = int(request.POST["borrow_id"])
        _borrow = Borrow.objects.get(id=b_id)
        _borrow.date = datetime.now()
        _borrow.status = "Returned"
        _borrow.save()
        return HttpResponseRedirect(reverse('App_library:returning'))
    borrows = Borrow.objects.all()
    return render(request, "App_library/return.html", {"borrows": borrows})

templates/App_library/books.html
{% extends 'App_library/main.html' %}
{% load static %}
{% load widget_tweaks %}
{% load custom_filters %}
{% block body %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <style>
        .paddy {
            padding: 10px !important;
            text-align: center !important;
        }

        .wrap-input100 {
            width: 100%;
            position: relative;
            border-bottom: 2px solid rgba(255, 255, 255, 0.24);
            margin-bottom: 30px;
        }

        .input100 {
            font-family: Poppins-Regular, sans-serif;
            font-size: 16px;
            color: #fff;
            line-height: 1.2;

            display: block;
            width: 100%;
            height: 45px;
            background: transparent;
            padding: 0 5px 0 38px;
        }

        /*---------------------------------------------*/
        .focus-input100 {
            position: absolute;
            display: block;
            width: 100%;
            height: 100%;
            top: 0;
            left: 0;
            pointer-events: none;
        }

        .focus-input100::before {
            content: "";
            display: block;
            position: absolute;
            bottom: -2px;
            left: 0;
            width: 0;
            height: 2px;

            -webkit-transition: all 0.4s;
            -o-transition: all 0.4s;
            -moz-transition: all 0.4s;
            transition: all 0.4s;

            background: #fff;
        }

        .focus-input100::after {
            font-family: Material-Design-Iconic-Font, serif;
            font-size: 22px;
            color: #fff;

            content: attr(data-placeholder);
            display: block;
            width: 100%;
            position: absolute;
            top: 6px;
            left: 0px;
            padding-left: 5px;

            -webkit-transition: all 0.4s;
            -o-transition: all 0.4s;
            -moz-transition: all 0.4s;
            transition: all 0.4s;
        }

        .input100:focus {
            padding-left: 5px;
        }

        .input100:focus {
            top: -22px;
            font-size: 18px;
        }

        .input100:focus {
            width: 100%;
        }
    </style>

    <div class="container">
        <div class="container" style="padding: 100px !important;" id="table-div">
            <div class="h1" id="header">All Books</div>
            <button type="button" id="add_book" class="btn btn-success bg-dark"
                    style="padding: 10px!important; background-color: #5cb85c!important; margin: 10px 0 10px 0 !important;"
                    onclick="openForm()">
                Add New Book
            </button>
            <button type="button" id="add_bookself" class="btn btn-success" onclick="openBookSelfForm()"
                    style="padding: 10px!important; background-color: #5cb85c!important; margin: 10px 0 10px 0 !important;">
                Add NewBook-self
            </button>
            <!------ Bootstrap 5 Table Starts --------->
            <table class="table table-hover" id="book-table">
                {% if books %}
                    <thead>
                    <tr style="text-align: center;">
                        <th scope="col" class="paddy">Book Title</th>
                        <th scope="col" class="paddy">Category</th>
                        <th scope="col" class="paddy">Author</th>
                        <th scope="col" class="paddy">Description</th>
                        <th scope="col" class="paddy">Available</th>
                        <th scope="col" class="paddy">Action</th>
                    </tr>
                    </thead>
                {% else %}
                    <h1 id="no_book">No Books In My Library</h1>
                {% endif %}
                <tbody>
                {% if books %}
                    {% for book in books %}
                        <tr style="text-align: center;">
                            <td class="paddy">{{ book.title }}</td>
                            <td class="paddy">{{ book.categories }}</td>
                            <td class="paddy">{{ book.author }}</td>
                            <td class="paddy">{{ book.description|range_filter|linebreaks }}</td>
                            <td class="paddy">{{ book.available }}</td>
                            <td class="paddy"><a class="btn btn-danger delbook_id"
                                                 href="{% url 'App_library:delete_book' book.id %}"
                                                 style="color: #ffffff!important;">Delete</a> /
                                <a href="{% url 'App_library:edit_book' pk=book.pk %}" data-id="{{ book.id }}"
                                   class="btn btn-warning editButton ebook_id" style="color: #ffffff!important;">
                                    Edit</a></td>
                        </tr>
                    {% endfor %}
                {% endif %}
                </tbody>
            </table>
            <!------ Table Ends ------->
            <div id="book_form" style="display:none;">
                <div class="row">
                    <div class="col-md-1"></div>
                    <div class="col-lg-10">
                        <form id="form" method="POST" action="{% url 'App_library:books' %}"
                              enctype="multipart/form-data">
                            {% csrf_token %}
                            <legend style="text-align: center; font-size: 30px; font-weight: 600;">New Book Form
                            </legend>
                            <fieldset class="form-group">
                                <div class="wrap-input100 validate-input" data-validate="Book Title">
                                    {% render_field form.title class="form-control input100" type="text" name="title" placeholder="Book title" %}
                                </div>
                                <div class="wrap-input100 validate-input" data-validate="Book Category">
                                    {% render_field form.categories class="form-control input100" type="text" name="category" placeholder="Category" %}
                                </div>
                                <div class="wrap-input100 validate-input" data-validate="Book Cover">
                                    {% render_field form.cover class="form-control input100" type="file" name="cover" placeholder="Cover" %}
                                </div>
                                <div class="wrap-input100 validate-input" data-validate="Author">
                                    {% render_field form.author class="form-control input100" type="text" name="author" placeholder="Book Author" %}
                                </div>
                                <div class="wrap-input100 validate-input" data-validate="Book Title">
                                    {% render_field form.description class="form-control input100" type="text" name="description" placeholder="Book Description" %}
                                </div>
                                <div class="wrap-input100 validate-input" data-validate="Available in store">
                                    {% render_field form.available class="form-control input100" type="text" name="available" placeholder="Available" %}
                                </div>
                                <div class="wrap-input100 validate-input" data-validate="Book-self No.">
                                    {% render_field form.location class="form-control input100" type="text" name="location" placeholder="Book-self No." %}
                                </div>
                            </fieldset>
                            <button name="save_book" id="save_book" type="submit" class="btn btn-primary mt-3"
                                    style="background: #5cb85c!important; padding: 10px!important;"><span
                                    class="glyphicon glyphicon-save"></span>
                                Submit
                            </button>
                        </form>
                    </div>
                    <div class="col-md-1"></div>
                </div>
            </div>
            <div id="bookself_form" style="display:none;">
                <div class="row">
                    <div class="col-md-1"></div>
                    <div class="col-lg-10">
                        <form id="form" method="POST" action="{% url 'App_library:books' %}"
                              enctype="multipart/form-data">
                            {% csrf_token %}
                            <legend style="text-align: center; font-size: 30px; font-weight: 600;">New BookSelf Form
                            </legend>
                            <fieldset class="form-group">
                                <div class="wrap-input100 validate-input" data-validate="Bookself Number">
                                    {% render_field bookself.self_no class="form-control input100" type="text" name="self_no" placeholder="Bookself Number" %}
                                </div>
                                <div class="wrap-input100 validate-input" data-validate="Self Row">
                                    {% render_field bookself.row_no class="form-control input100" type="text" name="row_no" placeholder="Row Number" %}
                                </div>
                            </fieldset>
                            <button name="save_bookself" id="save_book" type="submit" class="btn btn-primary mt-3"
                                    style="background: #5cb85c!important; padding: 10px!important;">
                                save
                            </button>
                        </form>
                    </div>
                    <div class="col-md-1"></div>
                </div>
            </div>
        </div>
    </div>

    <!----- JavaScript ----->
    <script>
        let bookForm = document.getElementById('book_form');
        let booktable = document.getElementById('book-table');
        let bookself_form = document.getElementById('bookself_form');

        function openForm() {
            booktable.style.display = 'none';
            bookForm.style.display = 'block';
            document.getElementById('header').style.display = 'none';
            document.getElementById('add_book').style.display = 'none';
            document.getElementById('add_bookself').style.display = 'none';
            document.getElementById('no_book').style.display = 'none';
        }

        function openBookSelfForm() {
            booktable.style.display = 'none';
            bookForm.style.display = 'none';
            document.getElementById('header').style.display = 'none';
            document.getElementById('add_book').style.display = 'none';
            document.getElementById('add_bookself').style.display = 'none';
            document.getElementById('no_book').style.display = 'none';
            bookself_form.style.display = 'block';
        }
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"
            integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js"
            integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc"
            crossorigin="anonymous"></script>
{% endblock %}

templates/App_library/category.html
{% extends 'App_library/main.html' %}
{% load static %}
{% load crispy_forms_filters %}
{% block body %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <style>
        .paddy {
            margin: 10px 0 10px 0 !important;
        }

        .paddy th {
            padding: 10px !important;
            text-align: center !important;
        }

        .paddy td {
            padding: 10px !important;
            text-align: center !important;
        }
    </style>
    <div class="container">
        <div class="container" style="padding: 100px !important;">
            <button type="button" id="add_category" class="btn mt-3 mb-3"
                    style="padding: 10px!important; background-color: lightpink!important; color: #000000" onclick="addBookFormOpen()">
                ADD NEW CATEGORY
            </button>
            <div class="h1 mt-3 mb-3" id="head-title" style="text-align: center;">All Category</div>
            <hr>
            <div class="container" id="table-container">
                <table class="table">
                    <thead class="alert-info text-center">
                    <tr class="paddy">
                        <th scope="col">Category</th>
                        <th scope="col">Action</th>
                    </tr>
                    </thead>
                    <tbody class="text-center">
                    {% for category in categories %}
                        <tr class="paddy">
                            <td>{{ category.title }}</td>
                            <td><a class="btn btn-danger"
                                   href="{% url 'App_library:delete_category' category.id %}">Delete</a>
                                <a href="{% url 'App_library:edit_category' category.id %}" data-id="{{ category.id }}"
                                   style="color: #66afe9!important;"
                                   class="btn btn-warning editButton ebook_id">
                                    Edit</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div id="edit_form"></div>
            <div id="category_form" style="display:none;">
                <div class="row">
                    <div class="col-lg-3"></div>
                    <div class="col-lg-6">
                        <form id="form" method="POST" action="{% url 'App_library:categories' %}">
                            {% csrf_token %}
                            <div class="form-group">
                                <label>Category Title:</label>
                                <input type="text" name="title" required="required" class="form-control"/>
                            </div>
                            <div class="form-group">
                                <button name="save_category" id="save_category" type="submit"
                                        class="btn btn-primary mt-3"
                                        style="background: #5cb85c!important; padding: 10px!important;">
                                    save
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        let head_title = document.getElementById('head-title');

        function addBookFormOpen() {
            document.getElementById('table-container').style.display = 'none';
            document.getElementById('category_form').style.display = 'block';
            document.getElementById('add_category').style.display = 'none';
            head_title.style.textAlign = 'center';
            head_title.innerText = 'Add New Category';

        }
    </script>
    <!------- JavaScript ------->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"
            integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js"
            integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc"
            crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://kit.fontawesome.com/b6f67b378e.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% endblock %}

templates/App_library/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>My Library</title>
    <style>
        .nav-first a img{
            width: 30px;
            height: 30px;
        }
        .nav-second {
            background-color: #b28bff;
        }

        .nav-link {
            color: #ffffff !important;
            font-weight: 600 !important;
        }

        .active {
            color: #ff0000!important;
        }
    </style>
</head>
<body>
<div class="container">
    <div class="container">
        <nav class="nav nav-first justify-content-end">
            <a class="nav-link" href="#">
                <img src="{% static 'images/icons/youtube.png' %}" alt="YouTube">
            </a>
            <a class="nav-link" href="#">
                <img src="{% static 'images/icons/facebook.png' %}" alt="facebook">
            </a>
            <a class="nav-link" href="#">
                <img src="{% static 'images/icons/linkedin.png' %}" alt="linkedIn">
            </a>
        </nav>
    </div>
</div>
<div class="container">
    <div class="container">
        <nav class="nav nav-second justify-content-center">
            <a class="nav-link" aria-current="page" href="{% url 'App_library:home' %}" id="home">Home</a>
            <a class="nav-link" aria-current="page" href="{% url 'App_library:categories' %}" id="book-cat">Book-Category</a>
            <a class="nav-link" aria-current="page" href="{% url 'App_library:books' %}" id="books">Books</a>
            <a class="nav-link" aria-current="page" href="{% url 'App_library:customers' %}" id="customer">Customers</a>
            <a class="nav-link" aria-current="page" href="{% url 'App_library:borrow' %}" id="borrow">Borrow-Book</a>
            <a class="nav-link" aria-current="page" href="{% url 'App_library:returning' %}" id="return">Return-Book</a>
            <a class="nav-link" aria-current="page" href="{% url 'App_login:logout' %}">Logout</a>
        </nav>
    </div>
</div>
<div class="container">
    {% block body %}
    {% endblock %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"
        integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js"
        integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc"
        crossorigin="anonymous"></script>
</body>
</html>